{% extends 'index.swig' %}

{% block pageContent %}
    <div class="home-pane container">
        <h1>
            Best of Welcomes to CannyKitchen!
        </h1>
        <h2>
            Mission
        </h2>
        <p>
            We hope to help the poor saps stuck in cooking hell.
        </p>
        <h2>
            Status
        </h2>
        <p>
            Only basic features have been implemented.
        </p>
    </div>
{% endblock %}