{% extends 'index.swig' %}

{% block pageContent %}
<div class="home-pane container">
    <h1>
        Helpful Links
    </h1>
    <a href="http://www.foodfacts.com/">Foodfacts</a>
    <p>A website about nutrient information of all food products.</p>
    <a href="http://ndb.nal.usda.gov/ndb/search/list">National Nutrient Database</a>
    <p>Nutrient database by United States Department of Agriculture.</p>
    <a href="http://www.foodnetwork.com/recipes.html">Food Network</a>
    <p>Food Network page on recipes and how-to-cook videos</p>
    <a href="http://www.onlineconversion.com/weight_volume_cooking.htm">Onlineconversion</a>
    <p>A webpage that converts an unit of measurement into another.</p>
    <a href="http://www.myfitnesspal.com/recipe/calculator">My Fitness Pal</a>
    <p>A handy webpage that calculates amount of calories per ingredients</p>
    <a href="http://www.gatech.edu/">Georgia Institute of Technology-Homepage</a>
    <p>Our project wss done as a Senior Project at Georgia Institute of Technology</p>
</div>
{% endblock %}