{% extends 'index.swig' %}

{% block pageContent %}
<div class="home-pane container">
    <h1>
        Helpful Links
    </h1>
    <a href="http://www.foodfacts.com/">Foodfacts</a>
    <p>A website about nutrient information of all food products.</p>
    <a href="http://ndb.nal.usda.gov/ndb/search/list">National Nutrient Database</a>
    <p>Nutrient database by United States Department of Agriculture</p>
</div>
{% endblock %}